// generated by optioner -type Waveform; DO NOT EDIT

// Please report issues and submit contributions at:
// http://github.com/akualab/optioner
// optioner is a project of AKUALAB INC.

package wav

// Option type is used to set options in Waveform.
type optWaveform func(*Waveform) optWaveform

// Option method sets the options. Returns previous option for last arg.
func (t *Waveform) Option(options ...optWaveform) (previous optWaveform) {
	for _, opt := range options {
		previous = opt(t)
	}
	return previous
}

// FS sets a value for instances of type Waveform.
func FS(o float64) optWaveform {
	return func(t *Waveform) optWaveform {
		previous := t.FS
		t.FS = o
		return FS(previous)
	}
}

// FrameSize sets a value for instances of type Waveform.
func FrameSize(o int) optWaveform {
	return func(t *Waveform) optWaveform {
		previous := t.frameSize
		t.frameSize = o
		return FrameSize(previous)
	}
}

// StepSize sets a value for instances of type Waveform.
func StepSize(o int) optWaveform {
	return func(t *Waveform) optWaveform {
		previous := t.stepSize
		t.stepSize = o
		return StepSize(previous)
	}
}
